name: Build & Artifacts

on:
  workflow_dispatch:
  pull_request:
    branches: main
env:
  IMAGE_NAME: nodejs-goof
  PLATFORM: linux-arm64
jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v6 
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.PLATFORM }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
      - name: Snyk Container
        run: |
          snyk container monitor ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.PLATFORM }} \
          --file=Dockerfile --exclude-app-vulns --platform=$${{ env.PLATFORM }} \
          --tags="component=pkg:${{ github.repository }}@${{ github.ref_name }}"
        continue-on-error: true

      - name: Snyk SBOM generate
        run: snyk container sbom --format=spdx2.3+json --name=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.PLATFORM }} --file=Dockerfile --platform=$${{ env.PLATFORM }} > bom.spdx.json
        continue-on-error: true

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: snyk SBOM
          path: bom.spdx.json
