name: Ensure Snyk Policy Version

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ensure .snyk policy version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure correct .snyk version exists
        run: |
          echo "${{ secrets.SNYK_SHA }}" | sha256sum --check -
          if [ $? -eq 0 ]; then
                echo ".snyk file is up-to-date."
              else
                echo ".snyk file was missing or outdated."
                echo $(cat .snyk)
              fi