name: Ensure Snyk Filter 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ensure Snyk Filter Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure snyk.yml exists in .snyk-filter directory
        run: |
          echo "${{ secrets.SNYK_SHA }}"" | sha256sum --check -
          if [ $? -eq 0 ]; then
                echo ".snyk file is up-to-date."
              else
                echo ".snyk file was missing or outdated."
                echo $(cat .snyk)
              fi