name: Ensure Snyk Policy Version

on:
  pull_request:
    branches: [main]

jobs:
  Check-Policy:
    name: Ensure Snyk Policy Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure correct .snyk version exists
        run: |
          echo "${{ secrets.SNYK_SHA }}" | sha256sum --check -
          if [ $? -eq 0 ]; then
                echo ".snyk file is up-to-date."
              else
                echo ".snyk file was missing or outdated."
                echo $(cat .snyk)
              fi
  # Trigger-Test:
  #   needs: Check-Policy
  #   name: Trigger Snyk test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - env:
  #         GH_TOKEN: ${{ secrets.MY_TOKEN }}
  #         SNYK_ACTION_NAME: ${{ secrets.SNYK_ACTION_NAME }}
  #       run: |
  #         gh workflow run $SNYK_ACTION_NAME
