name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        platforms: [linux/amd64, linux/arm64]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - 
        name: Generate Docker Tags
        id: docker_tags
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image-moby/buildkit:master
            network=host
          platforms: matrix.platforms
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}