name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    repo-name: nodejs-goof
jobs:
  build:
    strategy:
      matrix:
        platforms: [linux/amd64, linux/arm64]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - 
        name: Generate Docker Tags
        id: docker_tags
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.repo-name }}
          tags: |
            latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: matrix.platforms
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}