name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  SNYK_API: https://app.eu.snyk.io/api
  IMAGE_NAME: nodejs-goof
  
jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
        run: |
          npm install snyk -g
          npm install snyk-filter -g
          npm install snyk-to-html -g
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Setup the repo and install npm packages
        run: |
          npm install

      - name: Snyk Open Source
        run: |
          snyk test --json | snyk-filter || true
        # Run a snyk test and send the results into snyk-filter; failing on >2 high or >0 critical
        # Remove || true to fail if the criteria is met

      - name: Snyk Code
        run: |
          snyk code test || true
        # Remove || true to fail if there are vulnerabilities

      - name: Snyk Container
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          snyk container test ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }} --file=Dockerfile
        # Rename your image, for uploading directly to your snyk org please use the command "snyk container monitor $container_name/$tag --org=$ORG_ID"

      - name: Snyk IaC
        run: |
          snyk iac test || true
        # Remove || true to fail if there are vulnerabilities