name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: nodejs-goof
  
jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Build project
        run: npm ci --legacy-peer-deps

      - name: Setup Snyk + snyk-delta # For information about the required commands https://docs.snyk.io/scm-ide-and-ci-cd-integrations/snyk-ci-cd-integrations
        run: |
          npm install snyk snyk-delta -g
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Open Source
        run: snyk test --severity-threshold=medium # --json --print-deps | snyk-delta --setPassIfNoBaseline false
        # run: snyk monitor --org=XXX ---project-name=XXX - Use snyk monitor command to upload the results to the UI
        continue-on-error: true

      - name: Snyk Code
        run: snyk code test --report --project-name=nodejs-goof
        # snyk code test --report --project-name=XXX
        continue-on-error: true

      - name: Snyk Container
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          snyk container test ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }} --file=Dockerfile --exclude-app-vulns --platform=linux/amd64
        # Rename your image, for uploading directly to your snyk org please use the command "snyk container monitor $container_name/$tag --org=$ORG_ID"
        continue-on-error: true
      
      - name: Snyk IaC
        run: snyk iac test
        continue-on-error: true

      - name: Snyk SBOM generate
        run: snyk sbom --format=cyclonedx1.4+json --name=nodejs=goof --all-projects > bom.cyclonex1-4.json
        continue-on-error: true
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: snyk SBOM
          path: /bom.cyclonex1-4.json
